# Generated by Django 5.2 on 2025-04-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('kiongozi', 'Kiongozi'), ('mwananchi', 'Mwananchi')], default='mwananchi', max_length=20),
        ),
    ]
